# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/python/black
    rev: 19.10b0
    hooks:
    -   id: black

-   repo: https://github.com/sqlalchemyorg/zimports
    rev: master
    hooks:
    -   id: zimports

-   repo: https://github.com/pycqa/flake8
    rev: master
    hooks:
    -   id: flake8
        additional_dependencies:
          - flake8-import-order
          - flake8-builtins
          - flake8-docstrings
          - flake8-rst-docstrings
          - pydocstyle<4.0.0
          - pygments

